#连接mysql数据库
  spring:
    datasource:
      username: root
      password: 123456
      url: jdbc:mysql://localhost:3306/cmecplatform?useSSL=false&useUnicode=true&amp&characterEncoding=utf-8&serverTimezone=CTT
      driver-class-name: com.mysql.jdbc.Driver
    #模版配置
    thymeleaf:
      #避免修改模版后还要重启
      cache: false
      #模版路径，默认为templates（可忽略）
      prefix: classpath:/templates/
      #检查模版位置（可忽略）
      check-template-location: true
      #模版后缀，默认html（可忽略）
      suffix: .html
      encoding: UTF-8
      servlet:
        content-type: textml
      #模版模式
      mode: HTML
